<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('ApiBundle\\Controller\\DefaultController:userAuthCreateAction' => function () {
    return ${($_ = isset($this->services['service_locator.m7pz9ov']) ? $this->services['service_locator.m7pz9ov'] : $this->load(__DIR__.'/getServiceLocator_M7pz9ovService.php')) && false ?: '_'};
}, 'ApiBundle\\Controller\\DefaultController:userCreateAction' => function () {
    return ${($_ = isset($this->services['service_locator.m7pz9ov']) ? $this->services['service_locator.m7pz9ov'] : $this->load(__DIR__.'/getServiceLocator_M7pz9ovService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\LoginController:loginAction' => function () {
    return ${($_ = isset($this->services['service_locator.ssu7ap1']) ? $this->services['service_locator.ssu7ap1'] : $this->load(__DIR__.'/getServiceLocator_Ssu7ap1Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\RegisterController:registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.rvqcodq']) ? $this->services['service_locator.rvqcodq'] : $this->load(__DIR__.'/getServiceLocator_RvqcodqService.php')) && false ?: '_'};
}, 'ApiBundle\\Controller\\DefaultController::userAuthCreateAction' => function () {
    return ${($_ = isset($this->services['service_locator.m7pz9ov']) ? $this->services['service_locator.m7pz9ov'] : $this->load(__DIR__.'/getServiceLocator_M7pz9ovService.php')) && false ?: '_'};
}, 'ApiBundle\\Controller\\DefaultController::userCreateAction' => function () {
    return ${($_ = isset($this->services['service_locator.m7pz9ov']) ? $this->services['service_locator.m7pz9ov'] : $this->load(__DIR__.'/getServiceLocator_M7pz9ovService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\LoginController::loginAction' => function () {
    return ${($_ = isset($this->services['service_locator.ssu7ap1']) ? $this->services['service_locator.ssu7ap1'] : $this->load(__DIR__.'/getServiceLocator_Ssu7ap1Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\RegisterController::registerAction' => function () {
    return ${($_ = isset($this->services['service_locator.rvqcodq']) ? $this->services['service_locator.rvqcodq'] : $this->load(__DIR__.'/getServiceLocator_RvqcodqService.php')) && false ?: '_'};
})));
