<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5yjlvrb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5yjlvrb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5yjlvrb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5yjlvrb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5yjlvrb\appDevDebugProjectContainer(array(
    'container.build_hash' => '5yjlvrb',
    'container.build_id' => '1ff24da8',
    'container.build_time' => 1521750895,
));
