<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBccxxy7\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBccxxy7/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBccxxy7.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBccxxy7\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBccxxy7\appProdProjectContainer(array(
    'container.build_hash' => 'Bccxxy7',
    'container.build_id' => '56ccde4b',
    'container.build_time' => 1521018085,
));
