<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.profile' shared service.

include_once $this->targetDirs[3].'/vendor/twig/twig/lib/Twig/Profiler/Profile.php';

return $this->services['twig.profile'] = new \Twig\Profiler\Profile();
